apiVersion: v1
kind: Pod 
metadata: 
  name: pod-probe-2
  namespace: myns
  labels:
    app: myapp
    version: v1
spec:
  containers:
  - name: myapp-1
    image: docker.1ms.run/library/nginx:alpine

# kubectl create svc clusterip myapp --tcp=80:80 app=myapp