apiVersion: v1
kind: Pod 
metadata: 
  name: pod-probe-3
  namespace: myns
  labels:
    app: test
    version: v1
spec:
  containers:
  - name: myapp-1
    image: docker.1ms.run/library/nginx:alpine

