apiVersion: v1
kind: Pod 
metadata: 
  name: readiness-get-pod-1
  namespace: myns
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-1
    image: docker.1ms.run/library/nginx:alpine
    imagePullPolicy: IfNotPresent
    readinessProbe:
      httpGet:
        port: 80 
        path: /hostname.html
      initialDelaySeconds: 1
      periodSeconds: 3

