apiVersion: v1
kind: Pod 
metadata: 
  name: readiness-exec-pod-1
  namespace: myns
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-1
    image: docker.1ms.run/amd64/busybox:latest
    command: ["/bin/sh","-c","touch /tmp/live ; sleep 60 ; rm -rf /tmp/live ; sleep 20 "]
    imagePullPolicy: IfNotPresent
    readinessProbe:
      exec:
        command: ["test", "-e" , "/tmp/live"]
      initialDelaySeconds: 1
      periodSeconds: 3