apiVersion: v1
kind: Pod 
metadata: 
  name: lifecycle-get-pod-1
  namespace: myns
spec:
  containers:
  - name: myapp-1
    image: docker.1ms.run/library/nginx:alpine
    lifecycle:
      postStart:
        httpGet:
          host: 10.12.105.24
          path: index.html
          port: 80 
      preStop:
        httpGet:
          host: 10.12.105.24
          path: index.html
          port: 80 
